# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
#[[plugins]]
#repo = 'elzr/vim-json'
#if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# 括弧を補完
#[[plugins]]
#repo = 'Townk/vim-autoclose'

#閉じ括弧補完
#[[plugins]]
#repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
    let g:vim_json_syntax_conceal = 0
    au! BufRead,BufNewFile *.json set filetype=json
    augroup json_autocmd
        autocmd!
        autocmd FileType json set autoindent
        autocmd FileType json set formatoptions=tcq2l
        autocmd FileType json set textwidth=78 shiftwidth=2
        autocmd FileType json set softtabstop=2 tabstop=8
        autocmd FileType json set expandtab
        autocmd FileType json set foldmethod=syntax
    augroup END
'''

# Python plugins
[[plugins]]
repo = 'psf/black'
on_ft = ['python']
hook_add = '''
    autocmd BufWritePost *.py Black
'''
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']
hook_add = '''
    autocmd BufWritePost *.py call Flake8()
    let g:flake8_show_in_gutter=1
    let g:flake8_show_in_file=1
'''
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
[[plugins]]
repo = 'vim-scripts/syntastic'
on_ft = ['python']
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_ft = ['python']
hook_add = '''
    let g:auto_ctags = 1
    let g:auto_ctags_directory_list = ['.git', '.']
'''
