# 特定のファイルタイプで読み込む
[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# [[plugins]]
# repo   = 'Shougo/unite.vim'

# # unite.vim を読み込んだら一緒に読み込む
# [[plugins]]
# repo      = 'Shougo/neomru.vim'
# on_source = ['unite.vim']

# [[plugins]]
# repo = 'Shougo/neomru.vim'

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# depends = ['neomru.vim']
# on_event = 'BufRead'
# hook_add = '''
# nmap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>
# nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>
# nmap <silent> <C-u><C-j> :<C-u>Denite line<CR>
# nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
# nmap <silent> <C-u><C-]> :<C-u>DeniteCursorWord grep<CR>
# nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
# nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
# nmap <silent> <C-u><C-r> :<C-u>Denite -resume<CR>
# nmap <silent> <C-u>; :<C-u>Denite -resume -immediately -select=+1<CR>
# nmap <silent> <C-u>- :<C-u>Denite -resume -immediately -select=-1<CR>
# nmap <silent> <C-u><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
# nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
# '''
# hook_post_source = '''
# call denite#custom#var('file_rec', 'command',
# \ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
# call denite#custom#var('grep', 'command',
# \ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
# call denite#custom#var('grep', 'default_opts', [])
# call denite#custom#var('grep', 'recursive_opts', [])
# '''

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

# 特定のマッピングを使ったら読み込む
# 又、gvim でしか利用しない
[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1
